export const FETCH_TWEETS_START = 'FETCH_TWEETS_START';
export const FETCH_TWEETS_SUCCESS = 'FETCH_TWEETS_SUCCESS';
export const FETCH_TWEETS_ERROR = 'FETCH_TWEETS_ERROR';
export const FETCH_TWEETS = 'FETCH_TWEETS';

export const FETCH_TWEET_DETAILS_START = 'FETCH_TWEET_DETAILS_START';
export const FETCH_TWEET_DETAILS_SUCCESS = 'FETCH_TWEET_DETAILS_SUCCESS';
export const FETCH_TWEET_DETAILS_ERROR = 'FETCH_TWEET_DETAILS_ERROR';
export const FETCH_TWEET_DETAILS = 'FETCH_TWEET_DETAILS';