export const FETCH_TWEETS_START = 'FETCH_TWEETS_START';
export const FETCH_TWEETS_SUCCESS = 'FETCH_TWEETS_SUCCESS';
export const FETCH_TWEETS_ERROR = 'FETCH_TWEETS_ERROR';
export const FETCH_TWEETS = 'FETCH_TWEETS';